### ISSUE TITLE
[DataCap Application] Harvard LIL - 4 Projects (GBooks, CAP, H20, Perma)

### ISSUE THREAD

**Issue by johnhess** [filplus-bookkeeping/FF-Social-Impact#17]
### Data Owner Name

Harvard

### Data Owner Country/Region

United States

### Data Owner Industry

Education & Training

### Website

https://lil.law.harvard.edu/

### Social Media Handle

@HarvardLIL

### Social Media Type

Twitter

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

500TB

### Expected size of single dataset (one copy)

115TB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

1TB

### On-chain address for first allocation

f12e4cfbmcuomvwdirhvgzcgh7c6ggcpkqydih2wq

### Data Type of Application

Private Non-Profit / Social impact

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
About LIL:
==========
We are a software and design lab tucked inside the world's largest academic law library, building tools and communities for open knowledge. We build open-source software and web services, available to everyone and in the public interest, to explore and to solve emerging information problems from our shared perspective as librarians, programmers, artists, and lawyers. We currently support three long-running services ( Perma, H2O Open Casebook, and the Caselaw Access Project ) as well as a range of shorter term experiments.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
About the datasets:
===================

We are looking to onboard 4 datasets:

* Google Books Archive: ~75TB
* Caselaw Access Project: ~12TB (https://lil.law.harvard.edu/projects/caselaw-access-project/)
* H20: <1TB (https://lil.law.harvard.edu/projects/h2o/)
* Perma.cc: ~24TB (https://lil.law.harvard.edu/projects/perma-cc/)

At this time, we are looking for 1TB of DataCap for testing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
We will do it ourselves.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No.
```

### Please share a sample of the data

```text
I do not have samples with me at this time.  Links to 3 of the 4 datasources above point the way to public access data repositories though.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
Some of these datasets (i.e. the already public ones) can be public.  A portion of the Google Books dataset will need to be encrypted as it's not (yet) in the public domain.
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
I had some short discussions with a few providers via slack several months ago.  I would research again before selecting a final set.

Please share recommendations for SPs if you've got them.
```

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by johnhess** [comment]
@ianconsolata do I need to do anything else for this to get processed?

**Comment by ianconsolata** [comment]
Oh gosh, I forgot to watch this repo so I didn't get a notification. I can do this now.

**Comment by ianconsolata** [comment]
Encountered a bug when trying to sign the application, working it out with the tooling team now -- might take another day or two. Thanks for your patience.

**Comment by ianconsolata** [comment]
Closing in favor of #19
